################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
CPP_UPPER_SRCS := 
C++_UPPER_SRCS := 
CC_UPPER_SRCS := 
CPP_SRCS := 
O_SRCS := 
ELF_SRCS := 
CXX_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
CXX_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
CC_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
CC_UPPER_DEPS := 
C++_UPPER_DEPS := 
CPP_UPPER_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
JMP_UPPER_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
CXX_DEPS := 
JMP_DEPS := 
CXX_UPPER_DEPS := 
P_UPPER_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
PP_DEPS := 
CC_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
application_code/application/hwsetup \
application_code/application/hwsetup/octabus_setup/src \
application_code/common_demo/ota \
application_code/common_test/crypto \
application_code/common_test/devmode_key_provisioning \
application_code/common_test/framework \
application_code/common_test/freertos_tcp \
application_code/common_test/greengrass \
application_code/common_test/logging \
application_code/common_test/memory_leak \
application_code/common_test/mqtt \
application_code/common_test/ota \
application_code/common_test/pkcs11 \
application_code/common_test/secure_sockets \
application_code/common_test/shadow \
application_code/common_test/test_runner \
application_code/common_test/tls \
application_code \
application_code/renesas_code/application/Flash/rza2m-gr-mango \
application_code/renesas_code/application \
generate/compiler/asm \
generate/compiler/init \
generate/configuration \
generate/drivers/r_cache/src/lld \
generate/drivers/r_cpg/src/hld \
generate/drivers/r_cpg/src/lld \
generate/drivers/r_gpio/src/hld \
generate/drivers/r_gpio/src/lld \
generate/drivers/r_intc/src/lld \
generate/drivers/r_mmu/src/lld \
generate/drivers/r_stb/src/lld \
generate \
generate/os_abstraction/src \
generate/sc_drivers/r_adc/src/hld \
generate/sc_drivers/r_adc/src/lld \
generate/sc_drivers/r_cbuffer/src \
generate/sc_drivers/r_ether_gr_mango/src/phy \
generate/sc_drivers/r_ether_gr_mango/src \
generate/sc_drivers/r_ether_gr_mango/src/targets/rza2m-gr-mango \
generate/sc_drivers/r_octabus/src/lld \
generate/sc_drivers/r_ostm/src/hld \
generate/sc_drivers/r_ostm/src/lld \
generate/sc_drivers/r_riic/src/hld \
generate/sc_drivers/r_riic/src/lld \
generate/sc_drivers/r_scifa/src/hld \
generate/sc_drivers/r_scifa/src/lld \
generate/system \
lib/aws/FreeRTOS \
lib/aws/FreeRTOS/portable/GCC/ARM_CA9_RZA2M \
lib/aws/FreeRTOS/portable/MemMang \
lib/aws/FreeRTOS-Plus-TCP/source \
lib/aws/FreeRTOS-Plus-TCP/source/portable/BufferManagement \
lib/aws/FreeRTOS-Plus-TCP/source/portable/NetworkInterface/RZ \
lib/aws/bufferpool \
lib/aws/crypto \
lib/aws/greengrass \
lib/aws/mqtt \
lib/aws/ota \
lib/aws/ota/portable/renesas/rza2m-gr-mango \
lib/aws/pkcs11 \
lib/aws/secure_sockets \
lib/aws/shadow \
lib/aws/tls \
lib/aws/utils \
lib/third_party/jsmn \
lib/third_party/mbed_tls/library \
lib/third_party/tinycbor \
lib/third_party/unity/extras/fixture/src \
lib/third_party/unity/src \

