################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
CPP_UPPER_SRCS := 
C++_UPPER_SRCS := 
CC_UPPER_SRCS := 
CPP_SRCS := 
O_SRCS := 
ELF_SRCS := 
CXX_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
CXX_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
CC_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
CC_UPPER_DEPS := 
C++_UPPER_DEPS := 
CPP_UPPER_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
JMP_UPPER_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
CXX_DEPS := 
JMP_DEPS := 
CXX_UPPER_DEPS := 
P_UPPER_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
PP_DEPS := 
CC_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
generate/compiler/asm \
generate/compiler/init \
generate/configuration \
generate/drivers/r_cache/src/lld \
generate/drivers/r_cpg/src/hld \
generate/drivers/r_cpg/src/lld \
generate/drivers/r_gpio/src/hld \
generate/drivers/r_gpio/src/lld \
generate/drivers/r_intc/src/lld \
generate/drivers/r_mmu/src/lld \
generate/drivers/r_stb/src/lld \
generate \
generate/os_abstraction/src \
generate/sc_drivers/r_cbuffer/src \
generate/sc_drivers/r_octabus/src/lld \
generate/sc_drivers/r_ostm/src/hld \
generate/sc_drivers/r_ostm/src/lld \
generate/sc_drivers/r_scifa/src/hld \
generate/sc_drivers/r_scifa/src/lld \
generate/system \
gr_mango_boot \
src/renesas/application \
src/renesas/application/console \
src/renesas/application/hwsetup \
src/renesas/application/hwsetup/octabus_setup/src \
src/tinycrypt \
src/tinycrypt/lib \
src/tinycrypt/lib/source \
src/user_prog \

