################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
CPP_UPPER_SRCS := 
C++_UPPER_SRCS := 
CC_UPPER_SRCS := 
CPP_SRCS := 
O_SRCS := 
ELF_SRCS := 
CXX_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
CXX_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
CC_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
CC_UPPER_DEPS := 
C++_UPPER_DEPS := 
CPP_UPPER_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
JMP_UPPER_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
CXX_DEPS := 
LIBRARY_GENERATOR_OUTPUTTYPE_OUTPUTS := 
JMP_DEPS := 
CXX_UPPER_DEPS := 
P_UPPER_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
PP_DEPS := 
CC_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
application_code/application/console \
application_code/application/fatfs/source \
application_code/application/hwsetup \
application_code/application/hwsetup/octabus_setup/src \
application_code/common_demos/demo_runner \
application_code/common_demos/devmode_key_provisioning \
application_code/common_demos/logging \
application_code/common_demos/mqtt \
application_code/common_demos/ota \
application_code/common_demos/tcp \
application_code \
gr_mango_boot \
lib/aws/FreeRTOS \
lib/aws/FreeRTOS/portable/GCC/ARM_CA9_RZA2M \
lib/aws/FreeRTOS/portable/MemMang \
lib/aws/FreeRTOS-Plus-TCP/source \
lib/aws/FreeRTOS-Plus-TCP/source/portable/BufferManagement \
lib/aws/FreeRTOS-Plus-TCP/source/portable/NetworkInterface/RZ \
lib/aws/bufferpool \
lib/aws/cbor \
lib/aws/cbor/src \
lib/aws/crypto \
lib/aws/greengrass \
lib/aws/mqtt \
lib/aws/ota \
lib/aws/ota/portable/renesas/rza2m-gr-mango \
lib/aws/pkcs11/mbedtls \
lib/aws/pkcs11/portable/renesas/rza2m-gr-mango \
lib/aws/secure_sockets/portable/renesas/rza2m-gr-mango \
lib/aws/shadow \
lib/aws/tls \
lib/aws/utils \
lib/third_party/jsmn \
lib/third_party/mbedtls/source \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/amazon_freertos_common/Flash/rza2m-gr-mango \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/amazon_freertos_common \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/compiler/asm \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/compiler/init \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/configuration \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/drivers/r_cache/src/lld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/drivers/r_cpg/src/hld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/drivers/r_cpg/src/lld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/drivers/r_gpio/src/hld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/drivers/r_gpio/src/lld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/drivers/r_intc/src/lld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/drivers/r_mmu/src/lld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/drivers/r_stb/src/lld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/os_abstraction/src \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_adc/src/hld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_adc/src/lld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_cbuffer/src \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_ether_gr_mango/src/phy \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_ether_gr_mango/src \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_ether_gr_mango/src/targets/rza2m-gr-mango \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_octabus/src/lld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_ostm/src/hld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_ostm/src/lld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_riic/src/hld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_riic/src/lld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_scifa/src/hld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_scifa/src/lld \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_sdhi_simplified/fatfs_if \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_sdhi_simplified/src/sd/access \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_sdhi_simplified/src/sd/sdio \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/sc_drivers/r_sdhi_simplified/userdef \
lib/third_party/mcu_vendor/renesas/rz_mcu_boards/core_package/generate/system \
lib/third_party/tinycbor \

